name: Saanan API CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '10.0.x'
  API_PROJECT: 'SaananBE/src/ITServices.API/ITServices.API.csproj'

jobs:

  build:
    name: Build .NET API
    runs-on: ubuntu-latest

    steps:

      # 1. Get source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install .NET 10
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # 3. Restore NuGet packages
      - name: Restore
        run: dotnet restore ${{ env.API_PROJECT }}

      # 4. Build
      - name: Build
        run: dotnet build ${{ env.API_PROJECT }} --configuration Release --no-restore

      # 5. Publish
      - name: Publish
        run: dotnet publish ${{ env.API_PROJECT }} --configuration Release --no-build --output ./publish

      # 6. Upload published application
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: saanan-api
          path: ./publish
